<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>redaction-tool</AssemblyName>
    <RootNamespace>Toolkit.Tools.RedactionTool</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Toolkit.Core/Toolkit.Core.csproj" />
  </ItemGroup>
</Project>
